### ISSUE TITLE
Git issue on 32bit bot stops dipy installation early

### ISSUE THREAD

**Issue by Garyfallidis** [nipy/nibotmi#25]
http://nipy.bic.berkeley.edu/builders/dipy-bdist32-27/builds/301

STDIO output
 using PTY: False
<stdin>:738: trailing whitespace.
   candidates for this list.  
<stdin>:1064: trailing whitespace.
    
<stdin>:1097: trailing whitespace.
        
<stdin>:1139: trailing whitespace.
    
<stdin>:1156: trailing whitespace.
    
error: patch failed: .mailmap:29
error: .mailmap: patch does not apply
error: patch failed: .travis.yml:21
error: .travis.yml: patch does not apply
error: COPYING: does not exist in index
error: patch failed: Changelog:35
error: Changelog: patch does not apply
error: patch failed: MANIFEST.in:1
error: MANIFEST.in: patch does not apply
error: doc/source/_static/nibabel.css: does not exist in index
error: doc/source/_templates/indexsidebar.html: does not exist in index
error: doc/source/conf.py: does not exist in index
error: doc/source/devel/advanced_testing.rst: does not exist in index
error: doc/source/devel/devguide.rst: does not exist in index
error: doc/source/devel/index.rst: does not exist in index
error: doc/source/devel/make_release.rst: does not exist in index
error: doc/source/dicom/dcm2nii_algorithms.rst: does not exist in index
error: doc/source/gettingstarted.rst: does not exist in index
error: doc/source/images_and_memory.rst: does not exist in index
error: doc/source/index.rst: does not exist in index
error: doc/source/installation.rst: does not exist in index
error: doc/source/links_names.txt: does not exist in index
error: doc/source/nibabel_images.rst: does not exist in index
error: doc/source/nifti_images.rst: does not exist in index
error: doc/sphinxext/docscrape.py: already exists in index
error: doc/sphinxext/docscrape_sphinx.py: already exists in index
error: doc/sphinxext/math_dollar.py: already exists in index
error: doc/sphinxext/numpydoc.py: already exists in index
error: nibabel/__init__.py: does not exist in index
error: nibabel/externals/six.py: does not exist in index
error: nibabel/fileholders.py: does not exist in index
error: nibabel/freesurfer/mghformat.py: does not exist in index
error: nibabel/freesurfer/tests/test_mghformat.py: does not exist in index
error: nibabel/gifti/gifti.py: does not exist in index
error: nibabel/gifti/parse_gifti_fast.py: does not exist in index
error: nibabel/gifti/tests/test_parse_gifti_fast.py: does not exist in index
error: nibabel/info.py: does not exist in index
error: nibabel/nicom/dicomwrappers.py: does not exist in index
error: nibabel/nicom/tests/test_csareader.py: does not exist in index
error: nibabel/nicom/tests/test_dicomreaders.py: does not exist in index
error: nibabel/nicom/tests/test_dicomwrappers.py: does not exist in index
error: nibabel/nicom/tests/test_utils.py: does not exist in index
error: nibabel/openers.py: does not exist in index
error: nibabel/testing/__init__.py: does not exist in index
error: nibabel/tests/test_fileholders.py: does not exist in index
error: nibabel/tests/test_nifti1.py: does not exist in index
error: nibabel/tests/test_round_trip.py: does not exist in index
error: nibabel/tests/test_tripwire.py: does not exist in index
error: nibabel/trackvis.py: does not exist in index
error: nibabel/tripwire.py: does not exist in index
error: nibabel/xmlutils.py: does not exist in index
error: nisext/py3builder.py: does not exist in index
error: patch failed: requirements.txt:1
error: requirements.txt: patch does not apply
error: patch failed: setup.py:89
error: setup.py: patch does not apply

**Comment by Garyfallidis** [comment]
Same issue now on Python 3.3
http://nipy.bic.berkeley.edu/builders/dipy-bdist32-33/builds/208

**Comment by matthew-brett** [comment]
It looks like you're trying to run a `try_branch.py` run from the wrong repository, or where the repository is on a branch that is massively out of date.  Is that possible?

**Comment by matthew-brett** [comment]
Specifically it looks like you're trying to run `try_branch.py` from the nibabel repository.

**Comment by Garyfallidis** [comment]
I am definitely not doing that personally. But maybe some of the other devs is doing so.  @omarocegueda, @arokem, @marccote... Is it you guys?

**Comment by omarocegueda** [comment]
I'm currently not using try_branch. I'm trying to reproduce the Appveyor reported failure on a virtual machine... no luck so far =(

**Comment by arokem** [comment]
It's not me. @omarcegueda: thanks for putting the time in that. It's a real
annoying one - it seems intermittent too. For example, it passed just 3
days ago, when I rebased that branch:
https://ci.appveyor.com/project/arokem/dipy/build/1.0.584

**Comment by matthew-brett** [comment]
If y'all need to log into any of the buildbots directly, let me know.

**Comment by MarcCote** [comment]
Sorry guys, it was probably me. Yesterday, Matthew gave me access to the buildbot so I could debug a MemoryError of my nibabel's PR. I wasn't sure how to use try_branch.py and just pasted what Matthew sent me by email for the name of the bot. It tried to run a Nibabel patch on dipy-bdist32-27 !

**Comment by matthew-brett** [comment]
Oops - my fault for sending the wrong builder name...

**Comment by matthew-brett** [comment]
dipy-bdist32-33 error is something unrelated, not sure what caused it, I deleted the relevant directory and just reran the build:  http://nipy.bic.berkeley.edu/builders/dipy-bdist32-33/builds/210

**Comment by matthew-brett** [comment]
Meanwhile original buildbot has rerun its nightly build without error : http://nipy.bic.berkeley.edu/builders/dipy-bdist32-27/builds/303

So I think this issue can be closed.
